# This file configures TEM and MADS parameters for STEP4 of the calibration 
# EJ 03/02/23
calib_mode: GPPAllIgnoringNitrogen
# Calibration cases from the calibration/calibration_targets.py
# The output will be selected based on this cases
target_names: 
#- GPPAllIgnoringNitrogen
#- NPPAllIgnoringNitrogen
#- NPPAll
#- VegCarbon
#- VegStructuralNitrogen
#- MossDeathC
- CarbonShallow
- CarbonDeep
- CarbonMineralSum
#- OrganicNitrogenSum
- AvailableNitrogenSum
cmtnum: 1
opt_run_setup: --pr-yrs 100 --eq-yrs 2000 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0
params:
- micbnup 
- kdcrawc 
- kdcsoma 
- kdcsompr
- kdcsomcr
pftnums:
- None
- None
- None
- None
- None
site: /data/input-catalog/cru-ts40_ar5_rcp85_mri-cgcm3_MurphyDome_10x10
work_dir: /data/workflows/STEP4-MD1
mads_initial_guess:
- 0.4495   # micbnup: parameter for soil microbial immobialization of N  .64 
- 0.654    # kdcrawc: raw-material (litter) C decompositin rates at reference condition   .654
- 0.58     # kdcsoma:   0.58
- 0.003    # kdcsompr:   
- 0.000025 # kdcsomcr:
# NOTE: Kdcraw > Kdcactive > Kdcpr > Kdccr
mads_paramdist:
- Uniform(1e-1, 2.0)
- Uniform(1e-3, 0.99)
- Uniform(5e-3, 0.6)
- Uniform(1e-3, 0.25)
- Uniform(1e-7, 1e-4)
mads_paramkey:
- micbnup
- kdcrawc
- kdcsoma
- kdcsompr
- kdcsomcr
mads_obsweight:
mads_paramlog:
# mads_obsrange (ON, OFF) sets ranges for observations
mads_obsrange: 'OFF'
mads_obs_percent_variance: 1
# mads_paramrange (ON, OFF) sets ranges for parameters
mads_paramrange: 'OFF'
mads_param_percent_variance: 70
mads_problemname: AC3-STEP4-MD1-R-EJ-new
