# This file configures TEM and MADS parameters for STEP2 of the calibration 
# EJ 03/02/23
calib_mode: NPPVEGC
# Calibration cases from the calibration/calibration_targets.py
# The output will be selected based on this cases
target_names: 
#- GPPAllIgnoringNitrogen
#- NPPAllIgnoringNitrogen
- NPPAll
- VegCarbon
#- VegStructuralNitrogen
#- MossDeathC
#- CarbonShallow
#- CarbonDeep
#- CarbonMineralSum
#- OrganicNitrogenSum
#- AvailableNitrogenSum
cmtnum: 1
opt_run_setup: --pr-yrs 100 --eq-yrs 200 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0
params:
- nmax
- nmax
- nmax
- nmax
- krb(0)
- krb(0)
- krb(0)
- krb(0)
- krb(1)
- krb(1)
- krb(1)
- krb(2)
- krb(2)
- krb(2)
pftnums:
- 0
- 1
- 2
- 3
- 0
- 1
- 2
- 3
- 0
- 1
- 2
- 0
- 1
- 2
site: /data/input-catalog/cru-ts40_ar5_rcp85_mri-cgcm3_MurphyDome_10x10
work_dir: /data/workflows/STEP3-MD1-CR
mads_initial_guess:
- 2.95
- 1.45
- 1.07 
- 2.1
- -6.0
- -3.45 
- -2.95 
- -4.65
- -4.88
- -5.15
- -6.65
- -8.2 
- -6.2
- -3.2
mads_paramdist:
- Uniform(1, 5)
- Uniform(1, 5)
- Uniform(1, 5)
- Uniform(1, 5)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
- Uniform(-20, -0.1)
mads_paramkey:
- nmax0
- nmax1
- nmax2
- nmax3
- krb00
- krb01
- krb02
- krb03
- krb10
- krb11
- krb12
- krb20
- krb21
- krb22
mads_obsweight:
mads_paramlog:
# mads_obsrange (ON, OFF) sets ranges for observations
mads_obsrange: 'OFF'
mads_obs_percent_variance: 1
# mads_paramrange (ON, OFF) sets ranges for parameters
mads_paramrange: 'OFF'
mads_param_percent_variance: 70
mads_problemname: AC3-STEP3-MD1-R-EJ-new
